### ISSUE TITLE
Map<Integer, CustomObject> is deserialized as empty Map

### ISSUE THREAD

**Issue by flex-de** [research-virtualfortknox/msb-client-websocket-java#9]
Receiving an Object containing a Map (i.e. Map<Integer, CustomObject> via MSB function handler is not possible, because the data will be deserialized with an empty map.

When we receive the same JSON as a String (not as typed object) and perform the marshalling JSON to java object manually in our code, we can get the desired Map with all items mentioned in the JSON String.

Tested with:
Python websocket client -> MSB -> Java websocket client
Java websocket client -> MSB -> Java websocket client

**To Reproduce**
1. Create a function handler to receive an Object containing a Map<Integer, YourObject> as the desired type
2. Create a function handler to receive an Object containing a Map<Integer, YourObject> as String (raw JSON string)
3. Send an instanciated Map<Integer, YourObject> with at least one item (key-value pair) to the typed function of the java websocket client
4. Log received Map instance and check if Map contains any data
5. Send the same instanciated Map<Integer, YourObject> with at least one item (key-value pair) to the String-receiving function of the java websocket client and perform the marshalling in your code
6. log manually marshalled Map instance and check if Map contains any data
7. Compare both results. It must not be empty for both cases.

**Expected behavior**
When receiving a Map (or HashMap) the data should be deserialized as a filled Map with all the transmitted content (all items mentioned in the received JSON). This must be the case for Objects containing nested Maps (or HashMaps), too.

**Environment:**
 - MSB client version 1.0.1
 - MSB version 1.5.7-RELEASE

**Additional context**

########################################################
```java
@Log // lombok
@Component
@FunctionHandler(path = "/functionhandler")
public class MSBFunctionHandler {

    @FunctionCall(path = "/update", description = "", name = "update")
    public void update(@FunctionParam(name = "sortedItems") SortedItems sortedItems) throws Exception {
        log.info("List was empty: " + sortedItems.getTheListWithItems().isEmpty());
    }

    @FunctionCall(path = "/updateWithJSON", description = "", name = "updateWithJSON")
    public void updateWithJSON(@FunctionParam(name = "sortedItems") String jsonInput) throws Exception {
        log.fine("############# RAW JSON #############\n\n" + jsonInput + "\n\n");
        try {
            ObjectMapper mapper = new ObjectMapper();

            TypeReference<SortedItems> typeRef
                    = new TypeReference<SortedItems>() {};
            SortedItems items = mapper.readValue(jsonInput, typeRef);

            update(items);
        } catch (Exception e) {
            log.severe("Cannot handle raw JSON! " + e.getMessage() + "\n\n" + jsonInput + "\n\n");
            throw e;
        }

    }

}
```
########################################################
```java
@Data // lombok
public class SortedItems {

    Map<Integer, YourObject> theListWithItems;

}
```
########################################################
```java
@Data // lombok
public class YourObject {

    private String foo;
    private double bar;

}
```

**Comment by daniel-schel** [comment]
I have added a unit test which checks the deserialization of a map <K,V> and it works as expected.

**Comment by daniel-schel** [comment]
closed due to inactivity, if the problem still exists reopen the issue with further information
